runs:
  using: composite
  steps:
  - name: Cache Directory
    id: cache-dir
    shell: bash
    run: echo "aqua=${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}" >> $GITHUB_OUTPUT
  - name: Aqua Tools Cache
    uses: actions/cache@v3
    with:
      path: ${{ steps.cache-dir.outputs.aqua }}
      key: aqua-tools-${{ runner.os }}-${{ hashFiles('**/.aqua.yaml') }}
  - name: Setup Aqua
    uses: aquaproj/aqua-installer@v2.2.0
    with:
      aqua_version: v2.16.4
      aqua_opts: -a
